version: '3'
services:
  application:
    image: ${CI_REGISTRY_IMAGE}/application:${CI_COMMIT_TAG}
    restart: unless-stopped
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./.env:/var/www/.env
    working_dir: /var/www
    deploy:
      replicas: ${COMPOSE_REPLICAS:-1}
    networks:
      - database-network
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${IMAGE_NAME}-${APP_ENV}.entrypoints=http"
      - "traefik.http.routers.${IMAGE_NAME}-${APP_ENV}.rule=Host(`${APP_HOST}`)"
      - "traefik.http.middlewares.${IMAGE_NAME}-${APP_ENV}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${IMAGE_NAME}-${APP_ENV}.middlewares=${IMAGE_NAME}-${APP_ENV}-https-redirect"
      - "traefik.http.routers.${IMAGE_NAME}-${APP_ENV}-secure.entrypoints=https"
      - "traefik.http.routers.${IMAGE_NAME}-${APP_ENV}-secure.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.${IMAGE_NAME}-${APP_ENV}-secure.tls=true"
      - "traefik.http.routers.${IMAGE_NAME}-${APP_ENV}-secure.tls.certresolver=http"
      - "traefik.http.routers.${IMAGE_NAME}-${APP_ENV}-secure.service=${IMAGE_NAME}-${APP_ENV}"
      - "traefik.http.services.${IMAGE_NAME}-${APP_ENV}.loadbalancer.features.port=9000"
      - "traefik.docker.network=proxy"

#Docker Networks
networks:
  database-network:
    external: true
  proxy:
    external: true
