version: '3'
services:
  application:
    image: ${CI_REGISTRY_IMAGE}/application:${CI_COMMIT_TAG}
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: ${IMAGE_NAME}-${APP_ENV}-application
      SERVICE_TAGS: ${APP_ENV}
    working_dir: /var/www
    deploy:
      replicas: ${COMPOSE_REPLICAS:-1}
    networks:
      - database-network
    ports:
      - "${COMPOSE_PUBLIC_PORT}:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./.env:/var/www/.env


networks:
  database-network:
    external: true
